🐞 Installing Jammy: we need Python 3.11
Sometimes Python 3.10 isn't good enough.

Fixes, on Freedom SDK for Metal when running `pip install -r
requirements.txt`

```
Building wheels for collected packages: pylibfdt
  Building wheel for pylibfdt (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pylibfdt (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "/tmp/pip-build-env-vs4cehvl/overlay/lib/python3.10/site-packages/setuptools_scm/_integration/pyproject_reading.py", line 36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
      KeyError: 'setuptools_scm'
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building '_libfdt' extension
      swigging libfdt/libfdt.i to libfdt/libfdt_wrap.c
      swig -python -Ilibfdt -o libfdt/libfdt_wrap.c libfdt/libfdt.i
      creating build/temp.linux-x86_64-cpython-310/libfdt
      /home/scratch/jenkins-sw/workspace/freedom-tools/centos6-build/prebuilt/toolchain/x86_64-centos6-linux-gnu/bin/x86_64-centos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/scratch/jenkins-sw/workspace/freedom-tools/centos6-build/obj/x86_64-linux-centos6/install/msys64-buildtools-1.1.0-x86_64-linux-centos6/usr/xtras/include -I/home/scratch/jenkins-sw/workspace/freedom-tools/centos6-build/obj/x86_64-linux-centos6/install/msys64-buildtools-1.1.0-x86_64-linux-centos6/usr/xtras/include/ncursesw -fPIC -DPY_SSIZE_T_CLEAN -Ilibfdt -I/home/cunnie/wsFreedomStudio-4-0-8/sifive-fsfm_r2.0.21/venv/include -I/home/cunnie/FreedomStudio-4-0-8/SiFive/riscv-devutils-4.0.6/usr/include/python3.10 -c libfdt/fdt.c -o build/temp.linux-x86_64-cpython-310/libfdt/fdt.o
      error: command '/home/scratch/jenkins-sw/workspace/freedom-tools/centos6-build/prebuilt/toolchain/x86_64-centos6-linux-gnu/bin/x86_64-centos6-linux-gnu-gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pylibfdt
Failed to build pylibfdt
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pylibfdt)
```