🐞 AdoptOpenJDK8 requires special tap
fixes:
```
Error: Cask 'adoptopenjdk8' is unavailable: No Cask with this name exists.
Installing adoptopenjdk8 has failed!
```