Noble needs ffmpeg for 🤗 tutorials
Even though I did a `pip install ffmpeg`, I didn't realize I needed to
[also?] do a `apt install -y ffmpeg`

fixes:

```
ValueError: ffmpeg was not found but is required to load audio files from filename
```